# Default values for tt-clamav-rest.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: employmenttribunal.azurecr.io/tt-dss-a
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080


wsservice:
  type: ClusterIP
  port: 443

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: traefik-tt
  paths:
    - /
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
#  limits:
#   cpu: 200m
#   memory: 1500Mi
#  requests:
#   cpu: 100m
#   memory: 512Mi

nodeSelector: {}

tolerations: []

affinity: {}
