apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tt-wsproxy.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "tt-wsproxy.name" . }}
    helm.sh/chart: {{ include "tt-wsproxy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "tt-wsproxy.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "tt-wsproxy.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          volumeMounts:
          - name: config-volume
            mountPath: /opt/tomcat/conf/server.xml
            subPath: server.xml
          - name: test-volume
            mountPath: /opt/tomcat/webapps/ROOT/test.jsp
            subPath: test.jsp
          - name: keystore-volume
            mountPath: /opt/tomcat/keystore
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: ws
              containerPort: 4430
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- range $key, $value := $.Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: tomcat-server-config
            defaultMode: 420
        - name: test-volume
          configMap:
            name: tomcat-test
            items:
              - key: test.jsp
                path: test.jsp
                mode: 420
            defaultMode: 420
        - name: keystore-volume
          secret:
            secretName: keystore
            defaultMode: 256
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
